import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import AuthProvider from "./session-provider";
import { Header } from "@/components/header";

const soleilBold = localFont({
  src: "./fonts/SoleilBold.otf",
  variable: "--font-soleil-bold",
  weight: "100 900",
});
const soleilRegular = localFont({
  src: "./fonts/SoleilRegular.otf",
  variable: "--font-soleil",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${soleilRegular.variable} ${soleilBold.variable} antialiased`}
      >
        <AuthProvider>
        <Header />
        <section className="min-h-screen pt-10 bg-[#F8F5F2]">
            {children}
        </section>
        </AuthProvider>
      </body>
    </html>
  );
}
